### ISSUE TITLE
How can I use with dynamic url?

### ISSUE THREAD

**Issue by henyana** [meltingice/ajax-chosen#60]
It seem the beforeSend function is causing error compiling, here is my code:

$("select[name=element_id]").ajaxChosen({
    type: 'GET',
    url: '<?php echo site_url("wp_detail/get_elements");?>',
    dataType: 'json'
},
// beforeSend: function(xhr, s) {
//  s.data += "&newProp=newValue";
// },
    function (data) {
    console.log($(this));
    var terms = {};
    $.each(data.states, function (i, val) {
        terms[i] = val;
    });

```
return terms;
```

});

**Comment by carlosabs** [comment]
Man. you saved my life, been searching a while for this, just wrong answers around...
